@startuml
'https://plantuml.com/use-case-diagram

:Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml



Описание действий врача
@startuml

:Пациент:
:Врач:
:Администратор:

(Ввести симптомы)
(Получить прогноз области исследования)
(Изменить базу знаний)
(Добавить данные в базу знаний)
(Удалить данные из базы знаний)
(Удалить симптом)
(Удалить врача)
(Удалить правило)
(Добавить симптом)
(Добавить врача)
(Добавить правило)
(Дать обратную связь)


:Врач: -- (Ввести симптомы)
:Врач: -- (Получить прогноз области исследования)
:Врач: -- (Дать обратную связь)
:Врач: -- (Изменить базу знаний)

(Изменить базу знаний) <|-- (Добавить данные в базу знаний)
(Изменить базу знаний) <|-- (Удалить данные из базы знаний)

(Добавить данные в базу знаний) <|-- (Добавить симптом)
(Добавить данные в базу знаний) <|-- (Добавить правило)

(Удалить данные из базы знаний) <|-- (Удалить симптом)
(Удалить данные из базы знаний) <|-- (Удалить правило)

(Дать обратную связь)  ..> (Оценить корректность прогноза)
(Дать обратную связь)  ..> (Оценить корректность правил)


:Пациент: -- (Ввести симптомы)
:Пациент: -- (Получить прогноз области исследования)


:Администратор: -- (Добавить врача)
:Администратор: -- (Удалить врача)







@enduml

обобщение
<|--