# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThanksWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThanksWindow(object):
    def setupUi(self, ThanksWindow):
        ThanksWindow.setObjectName("ThanksWindow")
        #ThanksWindow.resize(620, 709)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ThanksWindow.sizePolicy().hasHeightForWidth())
        ThanksWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        ThanksWindow.setFont(font)
        ThanksWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        ThanksWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(ThanksWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_label.sizePolicy().hasHeightForWidth())
        self.main_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.main_label.setFont(font)
        self.main_label.setTextFormat(QtCore.Qt.AutoText)
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setWordWrap(False)
        self.main_label.setObjectName("main_label")
        self.verticalLayout_2.addWidget(self.main_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.button_layout = QtWidgets.QVBoxLayout()
        self.button_layout.setContentsMargins(-1, 10, -1, 10)
        self.button_layout.setSpacing(0)
        self.button_layout.setObjectName("button_layout")
        self.new_formul_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_formul_button.sizePolicy().hasHeightForWidth())
        self.new_formul_button.setSizePolicy(sizePolicy)
        self.new_formul_button.setMinimumSize(QtCore.QSize(0, 40))
        self.new_formul_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.new_formul_button.setObjectName("new_formul_button")
        self.button_layout.addWidget(self.new_formul_button)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMinimumSize(QtCore.QSize(0, 40))
        self.start_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.start_button.setObjectName("start_button")
        self.button_layout.addWidget(self.start_button)
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setMinimumSize(QtCore.QSize(0, 40))
        self.exit_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.exit_button.setObjectName("exit_button")
        self.button_layout.addWidget(self.exit_button)
        self.verticalLayout_2.addLayout(self.button_layout)
        ThanksWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ThanksWindow)
        QtCore.QMetaObject.connectSlotsByName(ThanksWindow)

    def retranslateUi(self, ThanksWindow):
        _translate = QtCore.QCoreApplication.translate
        ThanksWindow.setWindowTitle(_translate("ThanksWindow", "MainWindow"))
        self.main_label.setText(_translate("ThanksWindow", "Спасибо за обратную связь!"))
        self.new_formul_button.setText(_translate("ThanksWindow", "Добавить новую формулу в базу знаний"))
        self.start_button.setText(_translate("ThanksWindow", "Вернуться в начало"))
        self.exit_button.setText(_translate("ThanksWindow", "Выход"))
